services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ib-api
    ports:
      - "8000:8000"
    environment:
      IB_HOST: host.docker.internal
      IB_PORT: 4002
    restart: unless-stopped
